server:
  port: 10002

spring:
  application:
    name: service-business
    #服务应用名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  httpclient:
    connection-timeout: 3000
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
    #打开熔断器
    polling-interval-ms: 2000
    #刷新间隔